# Generated by Django 4.2.5 on 2023-10-26 19:39

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HealthFacilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, null=True)),
                ("healthcare", models.CharField(max_length=80, null=True)),
                ("amenity", models.CharField(max_length=80, null=True)),
                ("operatory", models.CharField(max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.MultiPointField(srid=4326),
                ),
            ],
        ),
    ]
